{{- if eq .Values.secrets.mode "externalSecret" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "campaign-platform.fullname" . }}-app-env
  labels:
    {{- include "campaign-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "campaign-platform.appEnvSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.secrets.externalSecret.remoteRefs.databaseUrl.key | quote }}
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.secrets.externalSecret.remoteRefs.postgresDb.key | quote }}
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.secrets.externalSecret.remoteRefs.postgresUser.key | quote }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.externalSecret.remoteRefs.postgresPassword.key | quote }}
{{- end }}
