global:
  imagePullPolicy: IfNotPresent
  nats:
    url: nats://campaign-platform-nats:4222
    subject: messages.dispatch
    retrySubject: messages.dispatch.retry
    deadLetterSubject: messages.dispatch.dead_letter
    stream: CAMPAIGN_MESSAGES
    useJetStream: "true"
  postgres:
    database: campaigns
    user: campaigns
    password: campaigns
    host: campaign-platform-postgres
    port: 5432

campaignApi:
  image:
    repository: campaign-api
    tag: local
  replicas: 1
  service:
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

providerSimulator:
  image:
    repository: provider-simulator
    tag: local
  replicas: 1
  service:
    port: 8080
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  providerMode: success
  latencyMs: "0"
  failureRate: "0.0"

dispatcher:
  image:
    repository: dispatcher
    tag: local
  replicas: 1
  service:
    port: 8080
  durable: dispatcher
  maxAttempts: "3"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

webUi:
  image:
    repository: web-ui
    tag: local
  replicas: 1
  service:
    port: 80
  apiBaseUrl: ""
  campaignApiUpstream: http://campaign-platform-campaign-api:8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 192Mi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

observability:
  serviceMonitor:
    enabled: true
    interval: 15s
  otel:
    enabled: true
    endpoint: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
    protocol: grpc

networkPolicy:
  enabled: true

postgres:
  image: postgres:16-alpine
  storage: 1Gi

redis:
  image: redis:7-alpine

nats:
  image: nats:2.10-alpine
